# Generated by Django 5.2.5 on 2025-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('props', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'ts'], name='analytics_e_name_e60151_idx'), models.Index(fields=['user_id', 'ts'], name='analytics_e_user_id_03e1be_idx')],
            },
        ),
    ]
