"""AUTH_USE
Django settings for EuroElite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v*cnfx@yx!0icme_h4+w+&ununtjqgrpp*=(f@r$)7ij+0&vyw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1','jehison.pythonanywhere.com','www.euroelite.cl','euroelite.cl']

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",                       # para pruebas locales sin https
    "https://jehison.pythonanywhere.com",     # pythonanywhere
    "https://sandbox.flow.cl",                # sandbox de Flow (borrar en produccion)
    "https://flow.cl",                        # Flow producción
    "https://www.euroelite.cl",               # dominio
    "https://euroelite.cl",                   # por si se usa sin www
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Main',
    'payments',
    'django.contrib.humanize',
    'analytics',
    'django.contrib.sites',
]

SITE_ID = 1


# Usuario personalizado
AUTH_USER_MODEL = 'Main.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
    # Analytics: middleware que captura page views y duración
    'analytics.middleware.PageViewMiddleware',
]


ROOT_URLCONF = 'EuroElite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EuroElite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'
USE_L10N = True

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "Main" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mirandaservicespa@gmail.com"
EMAIL_HOST_PASSWORD = "oxir ghig bqsp hrdj"
DEFAULT_FROM_EMAIL = "Euro Elite <mirandaservicespa@gmail.com>"



AUTHENTICATION_BACKENDS = [
    'Main.backends.BloqueoBackend',
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

FLOW_API_BASE = "https://sandbox.flow.cl/api"
FLOW_API_KEY = "4426F16C-1880-404C-A66D-6D9E24L18B4B".strip()
FLOW_SECRET_KEY = "4a12a875e3923de0efbc492f2a7787dc117eed14".strip()
FLOW_URL_CONFIRMATION = "https://www.euroelite.cl/pagos/flow/confirmacion/"
FLOW_URL_RETURN       = "https://www.euroelite.cl/pagos/flow/retorno/"

#importante para mantener sesión durante redirect de Flow
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Permite cookies en redirects externos
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS
SESSION_SAVE_EVERY_REQUEST = True  # Guarda sesión en cada request
SESSION_COOKIE_AGE = 86400  # 24 horas