# Generated by Django 5.2.5 on 2025-09-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_direccion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
