# Generated by Django 5.2.5 on 2025-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_cita_direccion_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('EN_PROCESO', 'En proceso')], default='RESERVADA', max_length=12),
        ),
    ]
