# Generated by Django 5.2.5 on 2025-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='accept_legal_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
