# Generated by Django 5.2.5 on 2025-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_usuario_accept_legal_terms_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
