# Generated by Django 5.2.5 on 2025-10-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
