# Generated by Django 5.2.5 on 2025-10-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_vehiculoenventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoenventa',
            name='combustible',
            field=models.CharField(choices=[('bencina', 'Bencina'), ('diesel', 'Diésel / Petrolero')], default='bencina', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculoenventa',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0, help_text='Kilómetros recorridos'),
        ),
        migrations.AddField(
            model_name='vehiculoenventa',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=20),
        ),
    ]
