# Generated by Django 5.2.5 on 2025-10-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_vehiculoenventa_combustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='combustible',
            field=models.CharField(choices=[('bencina', 'Bencina'), ('diesel', 'Diésel / Petrolero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='kilometraje',
            field=models.PositiveIntegerField(help_text='Kilómetros recorridos'),
        ),
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20),
        ),
    ]
