# Generated by Django 5.2.5 on 2025-10-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_vehiculoenventa_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='commerce_order',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='flow_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='flow_token',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
