# Generated by Django 5.2.5 on 2025-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_pago_commerce_order_pago_flow_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente')], db_index=True, default='CLIENTE', max_length=12),
        ),
    ]
