# Generated by Django 5.2.5 on 2025-10-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_pedido_options_pedido_asignado_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquehorario',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='bloquehorario',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='bloquehorario',
            name='profesional',
        ),
    ]
