# Generated by Django 5.2.5 on 2025-10-28 06:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_remove_bloquehorario_actualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO', 'Monto fijo')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de veces que se puede usar este código', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para aplicar el descuento', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FotoNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='nosotros/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foto de Nosotros',
                'verbose_name_plural': 'Fotos de Nosotros',
                'ordering': ['orden', '-creado'],
            },
        ),
        migrations.AddField(
            model_name='vehiculoenventa',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión por venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('MECANICO', 'Mecánico'), ('RETIRO', 'Encargado de Retiro'), ('DESPACHO', 'Encargado de Despacho'), ('REPARTIDOR', 'Repartidor')], db_index=True, default='CLIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Main.codigodescuento'),
        ),
        migrations.CreateModel(
            name='VehiculoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordatorioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('tiempo', 'Por tiempo'), ('kilometraje', 'Por kilometraje')], max_length=50)),
                ('fecha_programada', models.DateField()),
                ('kilometraje_programado', models.PositiveIntegerField(blank=True, null=True)),
                ('mensaje', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='Main.vehiculocliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('descripcion_trabajo', models.TextField()),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='en_espera', max_length=20)),
                ('comentario_mecanico', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='Main.cita')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Main.vehiculocliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
