# Generated by Django 5.2.5 on 2025-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_codigodescuento_contacto_fotonosotros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vendido', 'Vendido'), ('oculto', 'Oculto')], default='pendiente', max_length=20),
        ),
    ]
