# Generated by GitHub Copilot to align DB schema with models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_vehiculoenventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoenventa',
            name='patente',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehiculoenventa',
            name='color',
            field=models.CharField(max_length=30, blank=True, default=''),
        ),
    ]
