# Generated by Django 5.2.5 on 2025-10-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_add_patente_color_to_vehiculoenventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color del vehículo', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='patente',
            field=models.CharField(blank=True, default='', help_text='Patente del vehículo', max_length=10),
        ),
        migrations.CreateModel(
            name='VehiculoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Main.vehiculoenventa')),
            ],
            options={
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
