# Generated by Django 5.2.5 on 2025-11-03 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_vehiculoenventa_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='firma_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='receptor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='receptor_rut',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
