# Generated by Django 5.2.5 on 2025-11-11 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_codigodescuento_usos_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='Main.bloquehorario'),
        ),
    ]
