# Generated by Django 5.2.5 on 2025-11-25 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_alter_cita_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('MECANICO', 'Mecánico'), ('RETIRO', 'Encargado de Retiro'), ('DESPACHO', 'Encargado de Despacho'), ('REPARTIDOR', 'Repartidor'), ('ASIGNADOR', 'Asignador de pedidos')], db_index=True, default='CLIENTE', max_length=12),
        ),
    ]
