# Generated by Django 4.2.26 on 2025-11-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_horariodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('horario_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_disponibles', to='Main.horariodia')),
            ],
            options={
                'verbose_name_plural': 'Horas disponibles',
                'ordering': ('-fecha', 'hora'),
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
