# Generated by Django 4.2.26 on 2025-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_horadisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_total',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo real de los productos', max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ganancia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
