# Generated by Django 4.2.26 on 2025-11-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_testimonio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
