# Generated by Django 4.2.26 on 2025-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_alter_testimonio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='aprobada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
