# Generated by Django 4.2.26 on 2025-12-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_alter_testimonio_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculocliente',
            name='patente',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculoenventa',
            name='patente',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
